// Auth Action Types
module.exports.AUTH_START = 'AUTH_START'
module.exports.AUTH_SUCCESS = 'AUTH_SUCCESS'
module.exports.AUTH_FAILED = 'AUTH_FAILED'

// Product Action Types
module.exports.PROCESSING_PRODUCTS_START = 'PROCESSING_PRODUCTS_START'
module.exports.PROCESSING_PRODUCTS_FINISHED = 'PROCESSING_PRODUCTS_FINISHED'
module.exports.FETCH_PRODUCTS = 'FETCH_PRODUCTS'
module.exports.DELETE_PRODUCT = 'DELETE_PRODUCT'
module.exports.CREATE_PRODUCT = 'CREATE_PRODUCT'
module.exports.UPDATE_PRODUCT = 'UPDATE_PRODUCT'
